// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvdg565Bu9az1p_AM_FjUVHQgZUYzMYo',
    appId: '1:907931255654:web:eb17fe9edd72a8fa59bea7',
    messagingSenderId: '907931255654',
    projectId: 'expense-bc15f',
    authDomain: 'expense-bc15f.firebaseapp.com',
    storageBucket: 'expense-bc15f.appspot.com',
    measurementId: 'G-KNCKS519BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAa8AEKe7GT5WfDQqxhZRYPffm3tyLkE',
    appId: '1:907931255654:android:01bace42261fc8b359bea7',
    messagingSenderId: '907931255654',
    projectId: 'expense-bc15f',
    storageBucket: 'expense-bc15f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBt44nvkpGyav5RF_j3dNIm4tCKv7wC4',
    appId: '1:907931255654:ios:e7acb6cbb7cdc26059bea7',
    messagingSenderId: '907931255654',
    projectId: 'expense-bc15f',
    storageBucket: 'expense-bc15f.appspot.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdBt44nvkpGyav5RF_j3dNIm4tCKv7wC4',
    appId: '1:907931255654:ios:e7acb6cbb7cdc26059bea7',
    messagingSenderId: '907931255654',
    projectId: 'expense-bc15f',
    storageBucket: 'expense-bc15f.appspot.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvdg565Bu9az1p_AM_FjUVHQgZUYzMYo',
    appId: '1:907931255654:web:2294349fb2e1826359bea7',
    messagingSenderId: '907931255654',
    projectId: 'expense-bc15f',
    authDomain: 'expense-bc15f.firebaseapp.com',
    storageBucket: 'expense-bc15f.appspot.com',
    measurementId: 'G-FPECWJPTMD',
  );
}
